Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -11,14 +11,21 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
+      - name: Check if Dockerfile exists
+        run: |
+          if [ ! -f ./Dockerfile ]; then
+            echo "Dockerfile not found!"
+            exit 1
+          fi
+
       - name: Login to Docker Hub
         env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
 
-      - name: Build the Docker images
-        run: docker build -t front .
+      - name: Build the Docker image
+        run: docker build -t lucas8610/front .
 
       - name: Push to Dockerhub
         run: docker push lucas8610/front:latest
